import { INC } from 'store/slices/incidents/interfaces'
import { labelsForExcel } from '../../data'
import { convertTSToCurrentTZ } from 'utils/convertDate'

export const prepareDataINCs = (filtered: INC[]) => {
  const data = filtered.map(
    ({
      id,
      incident,
      numberINC,
      clientINC,
      status,
      sla,
      typeOfWork,
      timeSLA,
      client,
      legalName,
      contract,
      object,
      address,
      region,
      coordinates,
      equipment,
      model,
      typicalMalfunction,
      comment,
      description,
      timeRegistration,
      timeInWork,
      timeCloseCheck,
      timeClose,
      executor,
      responsible,
      userAccepted,
      userClosingCheck,
      userClosing,
      applicant,
      applicantContacts,
      typeCompletedWork,
      commentCloseCheck,
      commentClose,
      spaceParts,
      act,
      overdue,
      rating,
      parentalIncident,
      relatedIncident,
      methodsReuqest,
    }) => [
      id,
      incident,
      numberINC,
      clientINC,
      status,
      sla,
      typeOfWork,
      convertTSToCurrentTZ(timeSLA),
      client,
      legalName,
      contract,
      object,
      address,
      region,
      coordinates,
      equipment,
      model,
      typicalMalfunction,
      comment,
      description,
      convertTSToCurrentTZ(timeRegistration),
      convertTSToCurrentTZ(timeInWork),
      convertTSToCurrentTZ(timeCloseCheck),
      convertTSToCurrentTZ(timeClose),
      executor,
      responsible,
      userAccepted,
      userClosingCheck,
      userClosing,
      applicant,
      applicantContacts,
      typeCompletedWork,
      commentCloseCheck,
      commentClose,
      spaceParts && spaceParts.length > 0 ? spaceParts.join(', ') : spaceParts,
      act && act.length > 0 ? act.join(', ') : act,
      overdue,
      rating,
      parentalIncident,
      relatedIncident,
      methodsReuqest,
    ],
  )
  return [labelsForExcel, ...data]
}
