import {
  commentINCValidation,
  forSpacePartsValidation,
  lightTextValidation,
  NoRequiredValidation,
  phoneValidationNewINC,
} from 'utils/validatorRules'
import { INC_HeadCell, IOperator, methodsReuqest, Settings } from './interfaces'
import { IColumnOptions } from 'store/slices/tableINC/interfaces'

export const colorIndicator = {
  expired: '#f44336',
  notExpired: '#088208a3',
  inProgress: {
    more95: '#f44336',
    more75: '#efbb5aa3',
    more50: '#daf105',
  },
}

export const minHeaderColumnWidth = 40

export const labelsForExcel = [
  'ID',
  'Инцидент',
  'Номер',
  'Номер Клиента',
  'Статус',
  'Тип инцидента',
  'Тип работ',
  'Время SLA',
  'Клиент',
  'Клиент Юр',
  'Контракт',
  'Объект',
  'Адрес',
  'Регион',
  'Координаты',
  'Оборудование',
  'Модель',
  'Неисправность',
  'Комментарий',
  'Описание',
  'Время регистрации',
  'Время в работу',
  'Время выполнения',
  'Время закрытия',
  'Исполнитель',
  'Ответственный',
  'Кто принял',
  'Перевел в выполнение',
  'Закрыл',
  'Заявитель',
  'Контакты заявителя',
  'Тип выполненных работ',
  'Комментарии к выполнению',
  'Комментарии к закрытию',
  'ЗИП',
  'Акты',
  'Статус SLA',
  'Оценка',
  'Родительский',
  'Связанный',
  'Тип регистрации',
]

export const columnData: INC_HeadCell[] = [
  {
    number: 0,
    id: 'edit',
    label: '9998',
    type: 'custom',
    width: 40,
    minWidth: 40,
    maxWidth: 40,
    sortable: false,
    filterable: false,
    disableColumn: false,
    hideable: false,
    noChangeSettings: true,
  },
  {
    number: 1,
    id: 'indicator',
    label: 'SLA',
    type: 'custom',
    width: 60,
    minWidth: 60,
    maxWidth: 60,
    sortable: false,
    filterable: false,
    disableColumn: false,
    hideable: false,
    noChangeSettings: true,
  },
  {
    number: 2,
    id: 'id',
    label: 'ID',
    type: 'system',
    width: 50,
    minWidth: minHeaderColumnWidth,
    maxWidth: 50,
    sortable: false,
    filterable: false,
    disableColumn: true,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 3,
    id: 'incident',
    label: 'Инцидент',
    type: 'value',
    width: 125,
    minWidth: minHeaderColumnWidth,
    maxWidth: 125,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 4,
    id: 'numberINC',
    label: 'Номер',
    type: 'value',
    width: 90,
    minWidth: minHeaderColumnWidth,
    maxWidth: 90,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 5,
    id: 'clientINC',
    label: 'Номер Клиента',
    type: 'value',
    width: 140,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 6,
    id: 'timeSLA',
    label: 'Время SLA',
    type: 'dateTime',
    width: 130,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 7,
    id: 'status',
    label: 'Статус',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 8,
    id: 'client',
    label: 'Клиент',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 9,
    id: 'legalName',
    label: 'Клиент Юр',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 10,
    id: 'contract',
    label: 'Контракт',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 11,
    id: 'object',
    label: 'Объект',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 12,
    id: 'address',
    label: 'Адрес',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 1000,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 13,
    id: 'coordinates',
    label: 'Координаты',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 200,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 14,
    id: 'region',
    label: 'Регион',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 15,
    id: 'userAccepted',
    label: 'Кто принял',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 300,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 16,
    id: 'timeRegistration',
    label: 'Время регистрации',
    type: 'dateTime',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 17,
    id: 'sla',
    label: 'Тип инцидента',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 18,
    id: 'methodsReuqest',
    label: 'Тип регистрации',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 19,
    id: 'equipment',
    label: 'Оборудование',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 20,
    id: 'model',
    label: 'Модель',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 21,
    id: 'typicalMalfunction',
    label: 'Неисправность',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 22,
    id: 'executor',
    label: 'Исполнитель',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 23,
    id: 'responsible',
    label: 'Ответственный',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 24,
    id: 'timeInWork',
    label: 'Время в работу',
    type: 'dateTime',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 25,
    id: 'description',
    label: 'Описание',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 26,
    id: 'comment',
    label: 'Комментарий',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 27,
    id: 'applicant',
    label: 'Заявитель',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 28,
    id: 'applicantContacts',
    label: 'Контакты заявителя',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 29,
    id: 'userClosingCheck',
    label: 'Перевел в выполнение',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 30,
    id: 'timeCloseCheck',
    label: 'Время выполнения',
    type: 'dateTime',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 31,
    id: 'typeOfWork',
    label: 'Тип работ',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 32,
    id: 'typeCompletedWork',
    label: 'Тип выполненных работ',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 33,
    id: 'commentCloseCheck',
    label: 'Комментарии к выполнению',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 34,
    id: 'overdue',
    label: 'Статус SLA',
    type: 'boolean',
    width: 110,
    minWidth: minHeaderColumnWidth,
    maxWidth: 110,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 35,
    id: 'act',
    label: 'Акты',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 36,
    id: 'spaceParts',
    label: 'ЗИП',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 37,
    id: 'userClosing',
    label: 'Закрыл',
    type: 'list',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 38,
    id: 'timeClose',
    label: 'Время закрытия',
    type: 'dateTime',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 350,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 39,
    id: 'commentClose',
    label: 'Комментарии к закрытию',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 500,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 40,
    id: 'rating',
    label: 'Оценка',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 200,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 41,
    id: 'parentalIncident',
    label: 'Родительский',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 150,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
  {
    number: 42,
    id: 'relatedIncident',
    label: 'Связанный',
    type: 'value',
    width: 150,
    minWidth: minHeaderColumnWidth,
    maxWidth: 150,
    sortable: true,
    filterable: true,
    disableColumn: false,
    hideable: true,
    noChangeSettings: false,
  },
]

export const timeIntervalData = [
  { label: '- за 1 мес', value: 30 },
  { label: '- за 2 мес', value: 61 },
  { label: '- за 3 мес', value: 92 },
  { label: '- за 6 мес', value: 183 },
  { label: '- за 12 мес', value: 365 },
  { label: '- за 2 года', value: 730 },
  { label: '- за 3 года', value: 1095 },
  { label: '- за 5 лет', value: 1825 },
  { label: '- Все инциденты', value: 0 },
]

export const ModalTitles = {
  newIncident: 'Новый инцидент',
  newRequest: 'Новый запрос',
  newIncidentStatus: 'Новый статус инцидента',
  newTypesOfWork: 'Новый тип работ',
  newTypeCompletedWork: 'Новый тип выполненных работ',
  deleteIncidentStatuses: 'Удалить статус инцидента',
  deleteTypesOfWork: 'Удалить тип работ',
  deleteTypesCompletedWork: 'Удалить тип выполненных работ',
  changeIncidentStatuses: 'Изменить статус инцидента',
  changeTypesOfWork: 'Изменить тип работ',
  changeTypesCompletedWork: 'Изменить тип выполненных работ',
  closeINC: 'Закрытие инцидента',
  printINC: 'Выберите тип печати списка инцидентов',
  changeStateStatuses: 'Изменить порядок статусов инцидента',
  changeIncident: 'Изменить инцидент',
}

export const MapINCStatusInputFields = [
  {
    name: 'incStatus',
    label: 'Введите новый статус инцидента',
    validation: lightTextValidation,
    type: 'text',
    required: false,
  },
]

export const logicOperators = [
  { id: 1, logicOperator: 'and', logicOperatorLabel: 'И' },
  { id: 1, logicOperator: 'or', logicOperatorLabel: 'ИЛИ' },
]

export const operators: IOperator[] = [
  {
    id: 1,
    operator: 'contains',
    operatorLabel: 'содержит',
    needValue: true,
    value: '',
  },
  {
    id: 2,
    operator: 'doesNotContain',
    operatorLabel: 'не содержит',
    needValue: true,
    value: '',
  },
  {
    id: 3,
    operator: 'equals',
    operatorLabel: 'равно',
    needValue: true,
    value: '',
  },
  {
    id: 4,
    operator: 'doesNotEqual',
    operatorLabel: 'не равно',
    needValue: true,
    value: '',
  },
  {
    id: 5,
    operator: 'startsWith',
    operatorLabel: 'начинается с',
    needValue: true,
    value: '',
  },
  {
    id: 6,
    operator: 'endsWith',
    operatorLabel: 'заканчивается на',
    needValue: true,
    value: '',
  },
  {
    id: 7,
    operator: 'isEmpty',
    operatorLabel: 'пустой',
    needValue: true,
    value: '',
  },
  {
    id: 8,
    operator: 'isNotEmpty',
    operatorLabel: 'не пустой',
    needValue: true,
    value: '',
  },
]

export const DENISTY_OPTIONS: { label: string; value: boolean }[] = [
  { label: 'Компактный режим', value: true },
  { label: 'Стандартный режим', value: false },
]

export const SETTINGS_STORAGE_KEY = 'settings'

export const rowsPerPageOptions = [5, 10, 25, 50]

export const SETTINGS_DEFAULT: Settings = {
  dense: true,
  order: 'asc',
  orderBy: 'incident',
  page: 0,
  rowsPerPage: rowsPerPageOptions[2],
  showCellBorders: true,
  showColumnBorders: true,
  timeInterval: 92,
  selected: [],
  columnOptions: getColumnOptions(),
  filterListOptions: [
    {
      ...operators[0],
      column: columnData[3].id,
      columnLabel: columnData[3].label,
      columnType: columnData[3].type,
    },
  ],
}

export function getColumnOptions() {
  return columnData
    .map(item => {
      if (!item.noChangeSettings) {
        return {
          id: item.id,
          number: item.number,
          width: item.width,
          disableColumn: item.disableColumn,
          label: item.label,
          type: item.type,
        }
      }
    })
    .filter(item => item)
    .sort(
      (a, b) => (a?.number as number) - (b?.number as number),
    ) as IColumnOptions[]
}

export const MapINCInputFields = [
  {
    name: 'client',
    label: 'Выберите клиента',
    validation: NoRequiredValidation,
    type: 'text',
    required: true,
    // tabIndex: 1,
  },
  {
    name: 'contract',
    label: 'Выберите контракт',
    validation: NoRequiredValidation,
    type: 'dropdown',
    required: true,
    // tabIndex: 2,
  },
  {
    name: 'object',
    label: 'Выберите объект',
    validation: NoRequiredValidation,
    type: 'dropdown',
    required: true,
    // tabIndex: 3,
  },
  {
    name: 'equipment',
    label: 'Выберите классификатор',
    validation: NoRequiredValidation,
    type: 'dropdown',
    required: true,
    // tabIndex: 4,
  },
  {
    name: 'model',
    label: 'Выберите модель',
    validation: NoRequiredValidation,
    type: 'dropdown',
    required: true,
    // tabIndex: 5,
  },
  {
    name: 'typicalMalfunction',
    label: 'Выберите типовую неисправность',
    validation: NoRequiredValidation,
    type: 'dropdown',
    required: true,
    // tabIndex: 6,
  },
  {
    name: 'description',
    label: 'Введите описание к инциденту',
    validation: commentINCValidation,
    type: 'text',
    required: false,
    // tabIndex: 7,
  },

  {
    name: 'sla',
    label: 'Выберите SLA',
    validation: NoRequiredValidation,
    type: 'dropdown',
    required: true,
    // tabIndex: 8,
  },

  {
    name: 'timeSLA',
    label: 'Выберите время SLA',
    validation: NoRequiredValidation,
    type: 'datetime',
    required: true,
    // tabIndex: 9,
  },
  {
    name: 'typeOfWork',
    label: 'Выберите тип работ',
    validation: NoRequiredValidation,
    type: 'dropdown',
    required: true,
    // tabIndex: 10,
  },
  {
    name: 'cientINC',
    label: 'Введите клиентский номер',
    validation: NoRequiredValidation,
    type: 'text',
    required: false,
    // tabIndex: 11,
  },
  {
    name: 'applicant',
    label: 'Введите заявителя',
    validation: NoRequiredValidation,
    type: 'text',
    required: false,
    // tabIndex: 12,
  },
  {
    name: 'applicantContacts',
    label: 'Введите контакты заявителя',
    validation: phoneValidationNewINC,
    type: 'text',
    required: false,
    // tabIndex: 13,
  },
  {
    name: 'comments',
    label: 'Введите комментарии',
    validation: commentINCValidation,
    type: 'text',
    required: false,
    // tabIndex: 14,
  },
]

export const printTypeData = [
  { label: 'Нормальный', value: 'normal' },
  { label: 'Сжатый', value: 'compressed' },
  { label: 'Очень сжатый', value: 'xcompressed' },
]

export const MapTypesOfWorkInputFields = [
  {
    name: 'typesOfWork',
    label: 'Введите новый тип работ',
    validation: lightTextValidation,
    type: 'text',
    required: true,
  },
]

export const MapTypesCompletedWorkInputFields = [
  {
    name: 'typeCompletedWork',
    label: 'Введите новый тип выполненных работ',
    validation: lightTextValidation,
    type: 'text',
    required: true,
  },
]

export const MapINCStatusCloseInputFields = [
  {
    name: 'typeCompletedWork',
    label: 'Выберите тип выполненных работ',
    validation: NoRequiredValidation,
    type: 'dropdown',
    required: true,
  },
  {
    name: 'commentCloseCheck',
    label: 'Введите комментарии к закрытию инцидента',
    validation: commentINCValidation,
    type: 'text',
    required: true,
  },
  {
    name: 'act',
    label: 'Приложите акт',
    validation: NoRequiredValidation,
    type: 'text',
    required: false,
  },
  {
    name: 'spaceParts',
    label: 'Выберите ЗИП и подмену',
    validation: forSpacePartsValidation,
    type: 'text',
    required: false,
  },
]

export const empty_INCStatuses = [
  { statusINC: '', id: '', filterStatus: false, idFilter: 0 },
]

export const empty_INCExecutor = [
  { shortName: '', id: '', filterStatus: false, idFilter: 0 },
]

export const empty_INCResponsible = [
  { shortName: '', id: '', filterStatus: false, idFilter: 0 },
]

export const empty_INCClients = [
  { client: '', id: '', filterStatus: false, idFilter: 0 },
]

export const empty_INCContract = [
  { contract: '', id: '', filterStatus: false, idFilter: 0 },
]

export const empty_INClist = [
  { label: '', id: '', filterStatus: false, idFilter: 0 },
]

export const emptyExecutor = {
  shortName: '- Не назначен',
  id: 'executor_shortName_12345',
}

export const emptyResponsible = {
  shortName: '- Не назначен',
  id: 'responsible_shortName_12345',
}

export const emptyStatus = {
  id: '',
  incident: '',
  timeSLA: '',
  data: {
    label: '',
    id: '',
  },
  id_incStatus: '',
  status: '',
  userID: '',
  typeCompletedWork: {
    label: '',
    id: '',
  },
  commentCloseCheck: '',
  spaceParts: [],
}

export const emptyINC = {
  id: '',
  edit: '',
  indicator: '',
  numberINC: 0,
  incident: '',
  clientINC: '',
  status: '',
  client: '',
  contract: '',
  sla: '',
  typeOfWork: '',
  object: '',
  address: '',
  coordinates: '',
  region: '',
  userAccepted: '',
  equipment: '',
  model: '',
  typicalMalfunction: '',
  timeRegistration: '',
  timeInWork: '',
  timeSLA: '',
  timeCloseCheck: '',
  timeClose: '',
  executor: '',
  responsible: '',
  applicant: '',
  applicantContacts: '',
  userClosingCheck: '',
  userClosing: '',
  description: '',
  comment: '',
  report: '',
  spaceParts: [''],
  act: [''],
  active: false,
  typeCompletedWork: '',
  legalName: '',
  overdue: '',
  commentCloseCheck: '',
  commentClose: '',
  rating: '',
  parentalIncident: '',
  relatedIncident: '',
  methodsReuqest: methodsReuqest.manually,
}

export const logs = {
  timeGMT: 3,
  actionComment: {
    incidentRegistration: 'Зарегистрирован инцидент под номером ',
    changeExecutor: {
      first: 'Для инцидента под номером ',
      second: ' изменен исполнитель ',
    },
    changeResponsible: {
      first: 'Для инцидента под номером ',
      second: ' изменен ответственный ',
    },
    changeStatus: {
      first: 'Для инцидента под номером ',
      second: ' изменен статус ',
    },
  },
}

export const errEditINC = 'не может быть пустым!'
