export { NewClassifierEquipment } from './NewClassifierEquipment'
export { NewClassifierModel } from './NewClassifierModel'
export { NewTypicalMalfunction } from './NewTypicalMalfunction'
export { DeleteClassifierModel } from './DeleteClassifierModel'
export { DeleteClassifierEquipment } from './DeleteClassifierEquipment'
export { DeleteTypicalMalfunction } from './DeleteTypicalMalfunction'
export { ChangeTypicalMalfunction } from './ChangeTypicalMalfunction'
